<?php
/**
 * @file term_access.install
 * Install functions for the Term Access module.
 */

/**
 * Implements hook_enable().
 */
function term_access_enable() {
  drupal_set_message(t('Term Access enabled. Don\'t forget to visit the <a href="@url">settings page</a>.', array('@url' => url('admin/structure/taxonomy/term_access'))));
}

/**
 * Implements hook_uninstall().
 */
function term_access_uninstall() {
	variable_del('term_access_settings');
	variable_del('term_access_field');
}