<?php 

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function wysiwyg_mediaembed_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
   case 'ckeditor':
      return array(
        'MediaEmbed' => array(
          'buttons' => array(
             'MediaEmbed' => 'Media Embed',
          ),
          'path' => drupal_get_path('module', 'wysiwyg_mediaembed') . '/plugin/mediaembed',
          'url' => 'http://www.fluidbyte.net/index.php?view=embed-youtube-vimeo-etc-into-ckeditor',
          'load' => TRUE,
        ),
      );
  }
}
