<?php

/**
 * @file
 * Replace all expand tags by Multisite collapse ones.
 */

/**
 * Implements hook_menu().
 */
function jrc_expand_replace_menu() {
  $items = "";

  $items['admin/content/jrc_expand_replace'] = array(
    'title' => 'Replace expand tags',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jrc_expand_replace_default_form'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_form().
 */
function jrc_expand_replace_default_form($form, &$form_state) {

  $form = array();

  $form['range'] = array(
    '#type' => 'textfield',
    '#title' => t('Range'),
    '#default_value' => '1',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Replace'),
  );

  return $form;
}

/**
 * Implements hook_form_submit().
 */
function jrc_expand_replace_default_form_submit($form, &$form_state) {

  if (is_null($form_state['values']['range']) || $form_state['values']['range'] == 0) {
    $query = db_select('field_data_body', 'c')
      ->distinct()
      ->fields('c', array('entity_id'))
      ->condition('c.body_value', '%START_EXPAND%', 'like')
      ->orderBy('entity_id')
      ->execute();
  }
  else {
    $query = db_select('field_data_body', 'c')
      ->distinct()
      ->fields('c', array('entity_id'))
      ->condition('c.body_value', '%START_EXPAND%', 'like')
      ->range(0, $form_state['values']['range'])
      ->orderBy('entity_id')
      ->execute();
  }

  $count = 0;
  foreach ($query as $row) {
    // The node to modify.
    $thenode = node_load($row->entity_id);
    // Replace the expand tags.
    $thenode->body['und'][0]['value'] = str_replace('<div class="start_expand_editor">START_EXPAND</div>', '[collapsed]', $thenode->body['und'][0]['value']);
    $thenode->body['und'][0]['value'] = str_replace('<div class="end_expand_editor">END_EXPAND</div>', '[/collapse]', $thenode->body['und'][0]['value']);
    // Save node.
    node_save($thenode);
    $count++;
  }

  drupal_set_message(t('%count nodes having expand tags are updated', array('%count' => $count)));

  unset($query);
  unset($thenode);
  unset($count);
}
