<?php

/**
 * @file
 * Alters the menu item form to allow the administrator to specify additional
 * attributes for the menu link
 */

define('MENU_ATTRIBUTES_LINK', 'attributes');
define('MENU_ATTRIBUTES_ITEM', 'item_attributes');

/**
 * Implements hook_permission().
 */
function menu_attributes_permission() {
  return array(
    'administer menu attributes' => array(
      'title' => t('Administer menu attributes'),
      'description' => t('Administer menu attributes configuration.'),
    ),
  );
}

/**
 * Implements hook_menu_link_alter().
 */
function menu_attributes_menu_link_alter(&$item, $menu) {
  if (isset($item['options']['attributes']) && is_array($item['options']['attributes'])) {
    // Filter out blank attributes.
    foreach ($item['options']['attributes'] as $key => $value) {
      if ((is_array($value) && empty($value)) || is_string($value) && !drupal_strlen($value)) {
        unset($item['options']['attributes'][$key]);
      }
    }

    // Convert classes to an array.
    if (isset($item['options']['attributes']['class']) && is_string($item['options']['attributes']['class'])) {
      $item['options']['attributes']['class'] = array_filter(explode(' ', $item['options']['attributes']['class']));
    }
  }
}

/**
 * Implements hook_menu_attribute_info().
 */
function menu_attributes_menu_attribute_info() {
  //list of icons
  $icons = array(
    '' => 'None',
    'adjust' => 'adjust',
    'align-center' => 'align-center',
    'align-justify' => 'align-justify',
    'align-left' => 'align-left',
    'align-right' => 'align-right',
    'arrow-down' => 'arrow-down',
    'arrow-left' => 'arrow-left',
    'arrow-right' => 'arrow-right',
    'arrow-up' => 'arrow-up',
    'asterisk' => 'asterisk',
    'backward' => 'backward',
    'ban-circle' => 'ban-circle',
    'barcode' => 'barcode',
    'bell' => 'bell',
    'bold' => 'bold',
    'book' => 'book',
    'bookmark' => 'bookmark',
    'briefcase' => 'briefcase',
    'bullhorn' => 'bullhorn',
    'calendar' => 'calendar',
    'camera' => 'camera',
    'certificate' => 'certificate',
    'check' => 'check',
    'chevron-down' => 'chevron-down',
    'chevron-left' => 'chevron-left',
    'chevron-right' => 'chevron-right',
    'chevron-up' => 'chevron-up',
    'circle-arrow-down' => 'circle-arrow-down',
    'circle-arrow-left' => 'circle-arrow-left',
    'circle-arrow-right' => 'circle-arrow-right',
    'circle-arrow-up' => 'circle-arrow-up',
    'cloud' => 'cloud',
    'cloud-download' => 'cloud-download',
    'cloud-upload' => 'cloud-upload',
    'cog' => 'cog',
    'collapse-down' => 'collapse-down',
    'collapse-up' => 'collapse-up',
    'comment' => 'comment',
    'compressed' => 'compressed',
    'copyright-mark' => 'copyright-mark',
    'credit-card' => 'credit-card',
    'cutlery' => 'cutlery',
    'dashboard' => 'dashboard',
    'download' => 'download',
    'download-alt' => 'download-alt',
    'earphone' => 'earphone',
    'edit' => 'edit',
    'eject' => 'eject',
    'envelope' => 'envelope',
    'euro' => 'euro',
    'exclamation-sign' => 'exclamation-sign',
    'expand' => 'expand',
    'export' => 'export',
    'eye-close' => 'eye-close',
    'eye-open' => 'eye-open',
    'facetime-video' => 'facetime-video',
    'fast-backward' => 'fast-backward',
    'fast-forward' => 'fast-forward',
    'file' => 'file',
    'film' => 'film',
    'filter' => 'filter',
    'fire' => 'fire',
    'flag' => 'flag',
    'flash' => 'flash',
    'floppy-disk' => 'floppy-disk',
    'floppy-open' => 'floppy-open',
    'floppy-remove' => 'floppy-remove',
    'floppy-save' => 'floppy-save',
    'floppy-saved' => 'floppy-saved',
    'folder-close' => 'folder-close',
    'folder-open' => 'folder-open',
    'font' => 'font',
    'forward' => 'forward',
    'fullscreen' => 'fullscreen',
    'gbp' => 'gbp',
    'gift' => 'gift',
    'glass' => 'glass',
    'globe' => 'globe',
    'hand-down' => 'hand-down',
    'hand-left' => 'hand-left',
    'hand-right' => 'hand-right',
    'hand-up' => 'hand-up',
    'hd-video' => 'hd-video',
    'hdd' => 'hdd',
    'header' => 'header',
    'headphones' => 'headphones',
    'heart' => 'heart',
    'heart-empty' => 'heart-empty',
    'home' => 'home',
    'import' => 'import',
    'inbox' => 'inbox',
    'indent-left' => 'indent-left',
    'indent-right' => 'indent-right',
    'info-sign' => 'info-sign',
    'italic' => 'italic',
    'leaf' => 'leaf',
    'link' => 'link',
    'list' => 'list',
    'list-alt' => 'list-alt',
    'lock' => 'lock',
    'log-in' => 'log-in',
    'log-out' => 'log-out',
    'magnet' => 'magnet',
    'map-marker' => 'map-marker',
    'minus' => 'minus',
    'minus-sign' => 'minus-sign',
    'move' => 'move',
    'music' => 'music',
    'new-window' => 'new-window',
    'off' => 'off',
    'ok' => 'ok',
    'ok-circle' => 'ok-circle',
    'ok-sign' => 'ok-sign',
    'open' => 'open',
    'paperclip' => 'paperclip',
    'pause' => 'pause',
    'pencil' => 'pencil',
    'phone' => 'phone',
    'phone-alt' => 'phone-alt',
    'picture' => 'picture',
    'plane' => 'plane',
    'play' => 'play',
    'play-circle' => 'play-circle',
    'plus' => 'plus',
    'plus-sign' => 'plus-sign',
    'print' => 'print',
    'pushpin' => 'pushpin',
    'qrcode' => 'qrcode',
    'question-sign' => 'question-sign',
    'random' => 'random',
    'record' => 'record',
    'refresh' => 'refresh',
    'registration-mark' => 'registration-mark',
    'remove' => 'remove',
    'remove-circle' => 'remove-circle',
    'remove-sign' => 'remove-sign',
    'repeat' => 'repeat',
    'resize-full' => 'resize-full',
    'resize-horizontal' => 'resize-horizontal',
    'resize-small' => 'resize-small',
    'resize-vertical' => 'resize-vertical',
    'retweet' => 'retweet',
    'road' => 'road',
    'save' => 'save',
    'saved' => 'saved',
    'screenshot' => 'screenshot',
    'sd-video' => 'sd-video',
    'search' => 'search',
    'send' => 'send',
    'share' => 'share',
    'share-alt' => 'share-alt',
    'shopping-cart' => 'shopping-cart',
    'signal' => 'signal',
    'sort' => 'sort',
    'sort-by-alphabet' => 'sort-by-alphabet',
    'sort-by-alphabet-alt' => 'sort-by-alphabet-alt',
    'sort-by-attributes' => 'sort-by-attributes',
    'sort-by-attributes-alt' => 'sort-by-attributes-alt',
    'sort-by-order' => 'sort-by-order',
    'sort-by-order-alt' => 'sort-by-order-alt',
    'sound-5-1' => 'sound-5-1',
    'sound-6-1' => 'sound-6-1',
    'sound-7-1' => 'sound-7-1',
    'sound-dolby' => 'sound-dolby',
    'sound-stereo' => 'sound-stereo',
    'star' => 'star',
    'star-empty' => 'star-empty',
    'stats' => 'stats',
    'step-backward' => 'step-backward',
    'step-forward' => 'step-forward',
    'stop' => 'stop',
    'subtitles' => 'subtitles',
    'tag' => 'tag',
    'tags' => 'tags',
    'tasks' => 'tasks',
    'text-height' => 'text-height',
    'text-width' => 'text-width',
    'th' => 'th',
    'th-large' => 'th-large',
    'th-list' => 'th-list',
    'thumbs-down' => 'thumbs-down',
    'thumbs-up' => 'thumbs-up',
    'time' => 'time',
    'tint' => 'tint',
    'tower' => 'tower',
    'transfer' => 'transfer',
    'trash' => 'trash',
    'tree-conifer' => 'tree-conifer',
    'tree-deciduous' => 'tree-deciduous',
    'unchecked' => 'unchecked',
    'upload' => 'upload',
    'usd' => 'usd',
    'user' => 'user',
    'volume-down' => 'volume-down',
    'volume-off' => 'volume-off',
    'volume-up' => 'volume-up',
    'warning-sign' => 'warning-sign',
    'wrench' => 'wrench',
    'zoom-in' => 'zoom-in',
    'zoom-out' => 'zoom-out',
    );

  $info['data-image'] = array(
    'label' => t('Icon'),
    'description' => t('Specifies an icon to be displayed before the menu item. You can see the full ist of icons here: <a href="http://getbootstrap.com/components/#glyphicons">http://getbootstrap.com/components/#glyphicons</a>'),
    'form' => array(
      '#type' => 'select',
      '#options' => $icons,
    ),
  );
  $info['data-display-title'] = array(
    'label' => t('Display title'),
    'description' => t('Specifies if you want to display the title, or only an icon.'),
    'form' => array(
      '#type' => 'select',
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
    ),
  );  
  $info['title'] = array(
    'label' => t('Title'),
    'description' => t('The description displayed when hovering over the link.'),
    'form' => array(
      '#type' => 'textarea',
      '#rows' => 2,
    ),
    'scope' => array(MENU_ATTRIBUTES_LINK),
  );
  $info['data-hide-children'] = array(
    'label' => t('Hide children menu items'),
    'description' => t('If checked, children items of this menu item will never be displayed (mainly used when displaying menu blocks).'),
    'form' => array(
      '#type' => 'checkbox',
    ),
  );
  $info['id'] = array(
    'label' => t('ID'),
    'description' => t('Specifies a unique ID for the link.'),
    'scope' => array(MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM),
  );
  $info['name'] = array(
    'label' => t('Name'),
    'scope' => array(MENU_ATTRIBUTES_LINK),
  );
  $info['rel'] = array(
    'label' => t('Relationship'),
    'description' => t("Specifies the relationship between the current page and the link. Enter 'nofollow' here to nofollow this link."),
    'scope' => array(MENU_ATTRIBUTES_LINK),
  );
  $info['class'] = array(
    'label' => t('Classes'),
    'description' => t('Enter additional classes to be added to the link.'),
    'scope' => array(MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM),
  );
  $info['data-remove-class'] = array(
    'label' => t('Remove default classes'),
    'description' => t('Remove the default classes added on menu items, in ec_resp theme.'),
    'form' => array(
      '#type' => 'checkbox',
      ),
  );
  $info['style'] = array(
    'label' => t('Style'),
    'description' => t('Enter additional styles to be applied to the link.'),
    'scope' => array(MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM),
  );
  $info['target'] = array(
    'label' => t('Target'),
    'description' => t('Specifies where to open the link. Using this attribute breaks XHTML validation.'),
    'form' => array(
      '#type' => 'select',
      '#options' => array(
        '' => t('None (i.e. same window)'),
        '_blank' => t('New window (_blank)'),
        '_top' => t('Top window (_top)'),
        '_self' => t('Same window (_self)'),
        '_parent' => t('Parent window (_parent)'),
      ),
    ),
    'scope' => array(MENU_ATTRIBUTES_LINK),
  );
  $info['accesskey'] = array(
    'label' => t('Access Key'),
    'description' => t('Specifies a <a href="@accesskey">keyboard shortcut</a> to access this link.', array('@accesskey' => url('http://en.wikipedia.org/wiki/Access_keys'))),
    'form' => array(
      '#maxlength' => 1,
      '#size' => 1,
    ),
    'scope' => array(MENU_ATTRIBUTES_LINK),
  );
  return $info;
}

/**
 * Fetch an array of menu attributes.
 */
function menu_attributes_get_menu_attribute_info() {
  $attributes = module_invoke_all('menu_attribute_info');

  // Merge in default values.
  foreach ($attributes as $attribute => &$info) {
    $info += array(
      'form' => array(),
      'enabled' => variable_get("menu_attributes_{$attribute}_enable", 1),
      'default' => '',
    );
    $info['form'] += array(
      '#type' => 'textfield',
      '#title' => $info['label'],
      '#description' => isset($info['description']) ? $info['description'] : '',
      '#default_value' => variable_get("menu_attributes_{$attribute}_default", $info['default']),
    );
  }
  drupal_alter('menu_attribute_info', $attributes);

  return $attributes;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds menu attribute options to the edit menu item form.
 *
 * @see menu_edit_item()
 * @see _menu_attributes_form_alter()
 * @see menu_attributes_form_menu_edit_item_submit()
 */
function menu_attributes_form_menu_edit_item_alter(&$form, $form_state) {
  $item = $form['original_item']['#value'];
  _menu_attributes_form_alter($form, $item, $form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds menu attribute options to the node's edit menu item form.
 *
 * @see _menu_attributes_form_alter()
 */
function menu_attributes_form_node_form_alter(&$form, $form_state) {
  if (isset($form['menu']['link']) && isset($form['#node']->menu)) {
    $item = $form['#node']->menu;
    _menu_attributes_form_alter($form['menu']['link'], $item, $form);
  }
}

/**
 * Add the menu attributes to a menu item edit form.
 *
 * @param $form
 *   The menu item edit form passed by reference.
 * @param $item
 *   The optional existing menu item for context.
 */
function _menu_attributes_form_alter(array &$form, array $item = array(), array &$complete_form) {
  $form['options']['#tree'] = TRUE;
  $form['options']['#weight'] = 50;

  // Unset the previous value so that the new values get saved.
  unset($form['options']['#value']['attributes']);
  unset($form['options']['#value']['item_attributes']);

  $form['options'][MENU_ATTRIBUTES_LINK] = array(
    '#type' => 'fieldset',
    '#title' => t('Menu link attributes'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  );

  $form['options'][MENU_ATTRIBUTES_ITEM] = array(
    '#type' => 'fieldset',
    '#title' => t('Menu item attributes'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  );

  $attributes = menu_attributes_get_menu_attribute_info();
  foreach ($attributes as $attribute => $info) {
    // If no scope is set, this attribute should be available to both link
    // and item.
    if (!isset($info['scope'])) {
      $info['scope'] = array(MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM);
    }

    // Define fields for each scope.
    foreach ($info['scope'] as $group) {
      // Merge in the proper default value.
      if (isset($item['options'][$group][$attribute])) {
        // If the menu link already has this attribute, use it.
        $info['form']['#default_value'] = $item['options'][$group][$attribute];
        // Convert the classes array to a string for the form.
        if ($attribute == 'class' && is_array($info['form']['#default_value'])) {
          $info['form']['#default_value'] = implode(' ', $info['form']['#default_value']);
        }
      }
      elseif ($item['mlid']) {
        // If this is an existing link, use the raw default (usually empty).
        $info['form']['#default_value'] = $info['default'];
      }
      $form['options'][$group][$attribute] = $info['form'] + array(
        '#access' => $info['enabled'],
      );
    }
  }

  // Add form values for the reset of $item['options'] and
  // $item['options']['attributes'] so the values will carry over during save.
  foreach ($item['options'] as $key => $value) {
    if ($key !== 'attributes' && !isset($form['options'][$key])) {
      $form['options'][$key] = array(
        '#type' => 'value',
        '#value' => $value,
      );
    }
  }
  foreach (array(MENU_ATTRIBUTES_LINK, MENU_ATTRIBUTES_ITEM) as $group) {
    if (isset($item['options'][$group])) {
      foreach ($item['options'][$group] as $key => $value) {
        if (!isset($form['options'][$group][$key])) {
          $form['options'][$group][$key] = array(
            '#type' => 'value',
            '#value' => $value,
          );
        }
      }
    }
  }

  // Hide the 'description' field since we will be using our own 'title' field.
  if (isset($form['description'])) {
    $form['description']['#access'] = FALSE;

    // Because this form uses a special $form['description'] field which is
    // really the 'title' attribute, we need to add special pre-submit handling
    // to ensure our field gets saved as the title attribute.
    array_unshift($complete_form['#submit'], '_menu_attributes_form_submit');
  }

  // Restrict access to the new form elements.
  $has_visible_children = (bool) element_get_visible_children($form['options']['attributes']);
  $user_has_access = user_access('administer menu attributes');
  $form['options']['attributes']['#access'] = ($has_visible_children && $user_has_access);

  $has_visible_children = (bool) element_get_visible_children($form['options']['item_attributes']);
  $form['options']['item_attributes']['#access'] = ($has_visible_children && $user_has_access);
}

/**
 * Form submit handler for menu item links.
 *
 * Move the title attributes value into the 'description' value so that it
 * will get properly saved.
 */
function _menu_attributes_form_submit($form, &$form_state) {
  if (isset($form_state['values']['menu']['options']['attributes']['title'])) {
    $form_state['values']['menu']['description'] = $form_state['values']['menu']['options']['attributes']['title'];
  }
  elseif (isset($form_state['values']['options']['attributes']['title'])) {
    $form_state['values']['description'] = $form_state['values']['options']['attributes']['title'];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the menu settings form with our menu attribute settings.
 *
 * @see menu_configure_form()
 */
function menu_attributes_form_menu_configure_alter(&$form, $form_state) {
  if (!user_access('administer menu attributes')) {
    return;
  }

  $form['attributes_title'] = array(
    '#type' => 'item',
    '#title' => t('Menu item attribute options'),
  );
  $form['attributes_vertical_tabs'] = array(
    '#type' => 'vertical_tabs',
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'menu_attributes') . '/menu_attributes.js'),
    ),
  );

  $attributes = menu_attributes_get_menu_attribute_info();
  foreach ($attributes as $attribute => $info) {
    $form['attributes'][$attribute] = array(
      '#type' => 'fieldset',
      '#title' => $info['label'],
      '#group' => 'attributes_vertical_tabs',
      '#description' => $info['form']['#description'],
    );
    $form['attributes'][$attribute]["menu_attributes_{$attribute}_enable"] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable the @attribute attribute.', array('@attribute' => drupal_strtolower($info['label']))),
      '#default_value' => $info['enabled'],
    );
    $form['attributes'][$attribute]["menu_attributes_{$attribute}_default"] = array(
      '#title' => t('Default'),
      '#description' => '',
      '#states' => array(
        'invisible' => array(
          'input[name="menu_attributes_' . $attribute . '_enable"]' => array('checked' => FALSE),
        ),
      ),
    ) + $info['form'];
  }
}

/**
 * Implements MODULE_preprocess_HOOK().
 *
 * Adds appropriate attributes to the list item.
 *
 * @see theme_menu_link()
 */
function menu_attributes_preprocess_menu_link(&$variables) {
  $options = &$variables['element']['#localized_options'];
  $attributes = &$variables['element']['#attributes'];

  if (isset($options['item_attributes'])) {
    foreach ($options['item_attributes'] as $attribute => $value) {
      if (!empty($value)) {
        // Class get's special treatment, as it's an array and it should not
        // replace existing values.
        if ($attribute == 'class') {
          $value = !is_array($value) ? explode(' ', $value) : $value;
          if (isset($attributes[$attribute])) {
            $value = array_merge($attributes[$attribute], $value);
          }
        }
        // Override the attribute.
        $attributes[$attribute] = $value;
      }
    }

    // Clean up, so we're not passing this to l().
    unset($options['item_attributes']);
  }
}
