version: '2'
services:

  web:
    image: fpfis/php56-dev
    working_dir: /var/www/html
    ports:
      - 80:8080
    volumes:
      - .:/var/www/html
    environment:
      DOCUMENT_ROOT: /var/www/html/build
      XDEBUG_CONFIG: "remote_enable=1 remote_host=${DOCKER_HOST_IP} remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Test"

  mysql:
    image: fpfis/mysql56
