<?php
/**
 * @file
 * Context plugin file to provide changing the active theme as a context
 * reaction.
 */

/**
 * Implements hook_install().
 *
 * Set weight to 99 so we're one of the last modules to run. Can help with
 * timing in some cases (like og_subgroups)
 */
function context_reaction_theme_install() {
  db_update('system')
    ->fields(array('weight' => 99))
    ->condition('name', 'context_reaction_theme')
    ->execute();
}
